version: '2'
services:
  asocialnetwork:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /service/
#    volumes:
#      - ./src:/home/node/app
    ports:
      - "3000:3000"
    links:
      - asocialnetwork-service-mongo
  asocialnetwork-service-mongo:
    container_name: asocialnetwork-service-mongo
    image: mongo
    volumes:
      - ./data:/data/db